# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4278c4a3f966b8e07f5590a80d064061e2d32f664bb1266f760b4e930f9f0b64a039bc8858afcac89ce1cb0623c7ddf6308836f586f5872133c15e31576373

test:
  secret_key_base: c5a835074bfb83a04db41e1fdf3af92839639901430100cb94d342206fac822a4085e4c15bac1ce99874dfd4ce70a6713c45d1c4f86a3f6e0f5bfcd09c500fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
